version: '3'
services:
  mongo:
    container_name: mongo-db
    image: mongo:6.0
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    command: ['--auth']

volumes:
  mongo-db:
    external: true
